In [2]:
import tensorflow as tf
import tensorflow_probability as tfp
import keras
from keras import layers
import numpy as np
import matplotlib.pyplot as plt
import gym

In [6]:
from vae import VAE, create_decoder, create_encoder
from transition_gru import TransitionGRU
# from recurrent_agent import DAIFAgentRecurrent

In [7]:
from util import random_observation_sequence, transform_observations

In [8]:
enc = create_encoder(2, 2, [20])
dec = create_decoder(2, 2, [20])
# tran = TransitionGRU(2, 1)

env = gym.make('MountainCarContinuous-v0')

Metal device set to: Apple M1 Pro


2022-07-14 06:12:17.289691: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-07-14 06:12:17.289858: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [9]:
import tensorflow as tf
import tensorflow_probability as tfp
import keras
from keras import layers
import numpy as np


class TransitionGRU(keras.Model):

    def __init__(self, latent_dim, action_dim, seq_length, hidden_units, output_dim, batch_size=None, **kwargs):
        super(TransitionGRU, self).__init__(**kwargs)


        self.latent_dim = latent_dim
        self.action_dim = action_dim
        self.seq_length = seq_length
        self.hidden_units = hidden_units
        self.output_dim = output_dim

        self.batch_size = batch_size  # this should be number of policies I think


        inputs = layers.Input(shape=(None, self.latent_dim + self.action_dim))
        initial_state_input = layers.Input((self.hidden_units, ))
        h_states, final_state = layers.GRU(self.hidden_units, activation="tanh", return_sequences=True, return_state=True, name="gru")(inputs, initial_state=initial_state_input)

        # TODO is this correctly getting the last hidden state or the first???
        z_mean = layers.Dense(latent_dim, name="z_mean")(final_state)  # all batch last time step all dimension
        z_log_sd = layers.Dense(latent_dim, name="z_log_sd")(final_state)
        z_stddev = tf.exp(z_log_sd)

        self.transition_model = keras.Model([inputs, initial_state_input], [z_mean, z_stddev, final_state, h_states], name="transition")

        self.kl_loss_tracker = keras.metrics.Mean(name="kl_loss")


    def call(self, inputs, training=None, mask=None):

        # extract the initial state and
        x, initial_state = inputs
        if initial_state is None:
            initial_state = np.zeros((x.shape[0], self.hidden_units))  # start as zeros with number of examples times hidden dimension
        return self.transition_model([x] + [initial_state])


    @property
    def metrics(self):
        return [self.kl_loss_tracker]

    def train_step(self, data):
        # Unpack the data. Its structure depends on your model and
        # on what you pass to `fit()`.
        inputs, targets = data
        mu, stddev = targets
        x, init_states = inputs

        with tf.GradientTape() as tape:
            z_mean, z_stddev, final_state, h_states = self.transition_model([x, init_states], training=True)  # Forward pass

            # Compute the loss value
            pred_dist = tfp.distributions.MultivariateNormalDiag(loc=z_mean, scale_diag=z_stddev)
            true_dist = tfp.distributions.MultivariateNormalDiag(loc=mu, scale_diag=stddev)

            # TODO make sure this is the correct order of terms
            kl_loss = tfp.distributions.kl_divergence(pred_dist, true_dist)

        # Compute gradients
        trainable_vars = self.trainable_variables
        gradients = tape.gradient(kl_loss, trainable_vars)
        # Update weights
        self.optimizer.apply_gradients(zip(gradients, trainable_vars))
        # Update metrics (includes the metric that tracks the loss)
        self.kl_loss_tracker.update_state(kl_loss)
        return {
            "kl_loss": self.kl_loss_tracker.result()
        }


In [17]:
num_seqs = 1200
seq_length = 1
ob_seqs = []
next_obs = []

for i in range(num_seqs):
    o, a, r = random_observation_sequence(env, seq_length)

    train = np.concatenate([o[:-1], a], axis=1)
    test = o[-1]

    ob_seqs.append(train)
    next_obs.append(test)

ob_seqs = np.array(ob_seqs)
next_obs = np.array(next_obs)
ob_seqs.shape

ob_seqs_stddev = np.ones_like(ob_seqs)
next_obs_stddev = np.ones_like(next_obs)

ob_seqs.shape

(1200, 1, 3)

In [18]:
next_obs.shape

(1200, 2)

In [19]:
next_obs.shape

(1200, 2)

In [20]:
m = TransitionGRU(2, 1, 10, 30, 2)

m.compile(optimizer="Adam")
# m.build((None, None, 3))
# m.summary()
init_state = np.ones((1200, 30))

In [21]:
m.fit((ob_seqs, init_state), (next_obs, next_obs_stddev), batch_size=12, epochs=30)

Epoch 1/30


2022-07-14 06:13:55.046628: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-07-14 06:13:55.149664: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


 15/100 [===>..........................] - ETA: 0s - kl_loss: 0.1861

2022-07-14 06:13:55.287349: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


100/100 [==============================] - 1s 7ms/step - kl_loss: 0.0377
Epoch 2/30
100/100 [==============================] - 1s 7ms/step - kl_loss: 0.0016
Epoch 3/30
100/100 [==============================] - 1s 7ms/step - kl_loss: 0.0015
Epoch 4/30
100/100 [==============================] - 1s 7ms/step - kl_loss: 0.0015
Epoch 5/30
100/100 [==============================] - 1s 7ms/step - kl_loss: 0.0014
Epoch 6/30
100/100 [==============================] - 1s 7ms/step - kl_loss: 0.0013
Epoch 7/30
100/100 [==============================] - 1s 7ms/step - kl_loss: 0.0013
Epoch 8/30
100/100 [==============================] - 1s 7ms/step - kl_loss: 0.0012
Epoch 9/30
100/100 [==============================] - 1s 7ms/step - kl_loss: 0.0011
Epoch 10/30
100/100 [==============================] - 1s 7ms/step - kl_loss: 0.0011
Epoch 11/30
100/100 [==============================] - 1s 7ms/step - kl_loss: 0.0010
Epoch 12/30
100/100 [==============================] - 1s 7ms/step - kl_loss: 9.7100e

In [32]:
res = m((ob_seqs[0:10], None))
res[2]

<tf.Tensor: shape=(10, 30), dtype=float32, numpy=
array([[ 6.27587438e-02,  4.44589481e-02, -1.24372996e-01,
        -3.36149819e-02,  5.36136255e-02, -3.60391587e-02,
         5.27114607e-02,  5.75420149e-02, -1.83470901e-02,
        -7.76604787e-02,  1.59330724e-03,  7.37922862e-02,
         1.51956631e-02,  2.89747473e-02,  1.58253070e-02,
         6.28887191e-02, -8.27388689e-02, -6.44618319e-03,
        -3.82966152e-03,  8.23672712e-02,  8.48813448e-03,
        -5.32900617e-02, -8.57185870e-02,  4.17008847e-02,
         1.77301303e-01,  3.89871262e-02,  2.22239960e-02,
         6.31970763e-02,  5.49615826e-03, -5.33213019e-02],
       [ 3.91472876e-02,  8.34160522e-02, -1.51055992e-01,
        -5.09937666e-02,  6.21894635e-02,  1.04046213e-02,
         8.73814598e-02,  3.99699621e-02, -4.25067209e-02,
        -1.15755670e-01, -3.25602256e-02,  6.65052086e-02,
         3.84564884e-02,  6.19013887e-03,  4.12633680e-02,
         7.79162273e-02, -1.25306472e-01, -2.38631181e-02,
     

In [31]:
a = res[3].numpy()
a.shape

b = np.ones((1,1,30))

np.vstack([b,a]).shape

(11, 1, 30)

In [198]:
ob_seqs[0, :, :]

array([[-4.45428014e-01,  0.00000000e+00,  2.72747986e-02],
       [-4.45968002e-01, -5.40009467e-04, -3.52565408e-01],
       [-4.47613835e-01, -1.64583942e-03,  8.62713754e-02],
       [-4.49695230e-01, -2.08139676e-03,  8.96294475e-01],
       [-4.50981945e-01, -1.28670176e-03, -1.89263135e-01],
       [-4.53092873e-01, -2.11092504e-03, -5.68445802e-01],
       [-4.56581324e-01, -3.48845380e-03, -7.37783387e-02],
       [-4.60679710e-01, -4.09837300e-03,  8.02039087e-01],
       [-4.64044124e-01, -3.36441025e-03,  4.50792909e-02],
       [-4.67785209e-01, -3.74107878e-03,  1.37223557e-01],
       [-4.71737087e-01, -3.95189179e-03,  9.98514891e-02],
       [-4.75926608e-01, -4.18950990e-03,  4.93617922e-01],
       [-4.79732007e-01, -3.80540662e-03, -3.60979319e-01],
       [-4.84406948e-01, -4.67492733e-03,  8.04547429e-01],
       [-4.88168329e-01, -3.76136811e-03,  9.98299599e-01]])

In [199]:
tt = ob_seqs[0, :, :].reshape((1,15,3))
tt

array([[[-4.45428014e-01,  0.00000000e+00,  2.72747986e-02],
        [-4.45968002e-01, -5.40009467e-04, -3.52565408e-01],
        [-4.47613835e-01, -1.64583942e-03,  8.62713754e-02],
        [-4.49695230e-01, -2.08139676e-03,  8.96294475e-01],
        [-4.50981945e-01, -1.28670176e-03, -1.89263135e-01],
        [-4.53092873e-01, -2.11092504e-03, -5.68445802e-01],
        [-4.56581324e-01, -3.48845380e-03, -7.37783387e-02],
        [-4.60679710e-01, -4.09837300e-03,  8.02039087e-01],
        [-4.64044124e-01, -3.36441025e-03,  4.50792909e-02],
        [-4.67785209e-01, -3.74107878e-03,  1.37223557e-01],
        [-4.71737087e-01, -3.95189179e-03,  9.98514891e-02],
        [-4.75926608e-01, -4.18950990e-03,  4.93617922e-01],
        [-4.79732007e-01, -3.80540662e-03, -3.60979319e-01],
        [-4.84406948e-01, -4.67492733e-03,  8.04547429e-01],
        [-4.88168329e-01, -3.76136811e-03,  9.98299599e-01]]])

In [211]:

tt = ob_seqs[0, :, :].reshape((1,15,3))

single_seqs = tt.reshape((15, 1, 3))

# get hidden states
res = m((tt, None))

tf.reshape(res[3], (15, 30))

<tf.Tensor: shape=(15, 30), dtype=float32, numpy=
array([[ 0.05092128,  0.02318895, -0.01439999,  0.0412714 , -0.05107348,
        -0.02414587, -0.073426  ,  0.0296783 ,  0.01340997, -0.06062994,
         0.02914632,  0.0367431 , -0.0462583 ,  0.00397362, -0.03547276,
        -0.01210984, -0.05511517, -0.03319145, -0.04774348, -0.04823793,
        -0.06695485, -0.03089829,  0.05414404,  0.00973411,  0.02118521,
        -0.02880302, -0.03291158,  0.04922872,  0.06951188,  0.02279077],
       [ 0.04934441,  0.02994058, -0.01308529,  0.08643476, -0.12437439,
        -0.07959945, -0.08203309,  0.01460732,  0.03113721, -0.09456937,
        -0.01601063,  0.09491255, -0.10844023,  0.04893307, -0.03354961,
         0.01714423, -0.05211214, -0.06410497, -0.06149763, -0.06704654,
        -0.13511658, -0.09883294,  0.07920518,  0.02360793,  0.00803759,
        -0.06784516, -0.08920285,  0.05913128,  0.07914869, -0.01313069],
       [ 0.09322315,  0.05712149, -0.05186421,  0.09388846, -0.12795906,

In [212]:
res[3]

<tf.Tensor: shape=(1, 15, 30), dtype=float32, numpy=
array([[[ 0.05092128,  0.02318895, -0.01439999,  0.0412714 ,
         -0.05107348, -0.02414587, -0.073426  ,  0.0296783 ,
          0.01340997, -0.06062994,  0.02914632,  0.0367431 ,
         -0.0462583 ,  0.00397362, -0.03547276, -0.01210984,
         -0.05511517, -0.03319145, -0.04774348, -0.04823793,
         -0.06695485, -0.03089829,  0.05414404,  0.00973411,
          0.02118521, -0.02880302, -0.03291158,  0.04922872,
          0.06951188,  0.02279077],
        [ 0.04934441,  0.02994058, -0.01308529,  0.08643476,
         -0.12437439, -0.07959945, -0.08203309,  0.01460732,
          0.03113721, -0.09456937, -0.01601063,  0.09491255,
         -0.10844023,  0.04893307, -0.03354961,  0.01714423,
         -0.05211214, -0.06410497, -0.06149763, -0.06704654,
         -0.13511658, -0.09883294,  0.07920518,  0.02360793,
          0.00803759, -0.06784516, -0.08920285,  0.05913128,
          0.07914869, -0.01313069],
        [ 0.09322315,

In [208]:
tt

array([[[-4.45428014e-01,  0.00000000e+00,  2.72747986e-02],
        [-4.45968002e-01, -5.40009467e-04, -3.52565408e-01],
        [-4.47613835e-01, -1.64583942e-03,  8.62713754e-02],
        [-4.49695230e-01, -2.08139676e-03,  8.96294475e-01],
        [-4.50981945e-01, -1.28670176e-03, -1.89263135e-01],
        [-4.53092873e-01, -2.11092504e-03, -5.68445802e-01],
        [-4.56581324e-01, -3.48845380e-03, -7.37783387e-02],
        [-4.60679710e-01, -4.09837300e-03,  8.02039087e-01],
        [-4.64044124e-01, -3.36441025e-03,  4.50792909e-02],
        [-4.67785209e-01, -3.74107878e-03,  1.37223557e-01],
        [-4.71737087e-01, -3.95189179e-03,  9.98514891e-02],
        [-4.75926608e-01, -4.18950990e-03,  4.93617922e-01],
        [-4.79732007e-01, -3.80540662e-03, -3.60979319e-01],
        [-4.84406948e-01, -4.67492733e-03,  8.04547429e-01],
        [-4.88168329e-01, -3.76136811e-03,  9.98299599e-01]]])

In [204]:
res = m((tt, None))

vals = res[3]
vals.reshape((15, 30))

AttributeError: 
        'EagerTensor' object has no attribute 'reshape'.
        If you are looking for numpy-related methods, please run the following:
        from tensorflow.python.ops.numpy_ops import np_config
        np_config.enable_numpy_behavior()

In [171]:
m((ob_seqs[0:1, :, :], None))

[<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.56785977, -0.0094539 ]], dtype=float32)>,
 <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[0.99687016, 0.99474823]], dtype=float32)>,
 <tf.Tensor: shape=(1, 30), dtype=float32, numpy=
 array([[-0.0170462 ,  0.17420371, -0.16205727,  0.1459884 , -0.31527486,
         -0.00659207,  0.0312416 ,  0.0813532 ,  0.11589594, -0.34983537,
          0.09985405,  0.24849527, -0.12736231,  0.2578114 ,  0.06988851,
          0.02357278, -0.15019439,  0.01852169, -0.2631799 ,  0.25204396,
         -0.2779762 , -0.22705497,  0.35386953, -0.05633114,  0.06359442,
         -0.03013663, -0.14228506,  0.07216896,  0.1793234 ,  0.11629379]],
       dtype=float32)>,
 <tf.Tensor: shape=(1, 15, 30), dtype=float32, numpy=
 array([[[ 0.02425387,  0.0244065 , -0.0065957 ,  0.05379898,
          -0.07875035, -0.04081128, -0.02774346,  0.00961666,
           0.01717799, -0.05475242,  0.01146767,  0.09475566,
          -0.0658425 ,  0.04575911,  0.0

In [340]:
res[2]

<tf.Tensor: shape=(10, 30), dtype=float32, numpy=
array([[ 1.76516443e-01,  1.54475287e-01, -5.12306057e-02,
         1.64845765e-01,  2.68837273e-01, -9.95857716e-02,
         7.79657215e-02, -1.10403851e-01, -1.08879849e-01,
        -1.22801609e-01,  3.41023579e-02, -8.55413154e-02,
         1.35252342e-01, -5.53389899e-02, -2.05101758e-01,
         9.60189849e-02, -2.62633413e-01,  2.84929663e-01,
         2.07988352e-01, -1.35656670e-01,  1.67700097e-01,
        -9.03860945e-03,  9.67715830e-02,  1.41193375e-01,
        -1.73646688e-01, -1.49096355e-01,  1.63787216e-01,
         1.34333670e-01, -1.35705829e-01, -1.85656726e-01],
       [-4.13602814e-02,  1.25444561e-01,  1.13072321e-01,
         5.97583316e-02,  1.48286954e-01, -1.09492682e-01,
        -6.71713203e-02, -1.93654671e-01, -2.18552351e-01,
        -1.57539248e-01,  1.89289406e-01, -2.24954244e-02,
         1.34446856e-03, -4.91290167e-03, -2.39228070e-01,
         1.89485967e-01, -3.58797014e-01,  2.12003320e-01,
     

In [341]:
res[3]

<tf.Tensor: shape=(10, 5, 30), dtype=float32, numpy=
array([[[ 0.08676665,  0.0665729 , -0.01751424, ...,  0.04447326,
         -0.01017037, -0.07514461],
        [ 0.04867286,  0.10080533,  0.05040885, ...,  0.05720273,
         -0.10691113, -0.10694263],
        [ 0.15783645,  0.12385118, -0.07167391, ...,  0.10117968,
         -0.06072072, -0.15788542],
        [ 0.20955351,  0.14058515, -0.09838694, ...,  0.12855455,
         -0.07163367, -0.1843247 ],
        [ 0.17651644,  0.15447529, -0.05123061, ...,  0.13433367,
         -0.13570583, -0.18565673]],

       [[ 0.15751047,  0.06191986, -0.11045828, ...,  0.06034369,
          0.04968761, -0.08267669],
        [ 0.08696802,  0.09508388,  0.00635655, ...,  0.06304765,
         -0.08224013, -0.10179211],
        [-0.00656156,  0.11269982,  0.09019252, ...,  0.05995458,
         -0.1843041 , -0.10718634],
        [-0.00765619,  0.12198227,  0.07892087, ...,  0.07446641,
         -0.1967938 , -0.12551175],
        [-0.04136028,  0.12

In [255]:
# def gru(input_dim, seq_length, hidden_units, output_dim):
#
#     inputs = layers.Input(shape=(None, input_dim), batch_size=10)
#     out_states, h_states, *everything_else = layers.GRU(hidden_units, activation="tanh", stateful=True, return_sequences=True)(inputs)
#     h = layers.Dense(output_dim)(out_states)
#
#     model = keras.Model(inputs, h)
#
#     return model, h_states


input_dim = 3
hidden_units = 30
seq_length = 10
output_dim = 2


inputs = layers.Input(shape=(None, input_dim))
out_states = layers.GRU(2, activation="tanh", stateful=False, return_sequences=True)(inputs)
h = layers.Dense(output_dim)(out_states)

m = keras.Model(inputs, [h, out_states])

inputs2 = layers.Input(shape=(None, input_dim), batch_size=20)
out_states2 = layers.GRU(2, activation="tanh", stateful=False, return_sequences=False)(inputs2)
h2 = layers.Dense(output_dim)(out_states2)

m2 = keras.Model(inputs2, h2)

In [256]:
# m, h_states = gru(3, 10, 30, 2)

m.compile(optimizer="Adam", loss=tf.keras.losses.MeanSquaredError())
m.summary()

Model: "model_47"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_86 (InputLayer)       [(None, None, 3)]         0         
                                                                 
 gru_77 (GRU)                (None, None, 2)           42        
                                                                 
 dense_37 (Dense)            (None, None, 2)           6         
                                                                 
Total params: 48
Trainable params: 48
Non-trainable params: 0
_________________________________________________________________


In [237]:
m2.compile(optimizer="Adam", loss=tf.keras.losses.MeanSquaredError())
m2.summary()

Model: "model_40"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_77 (InputLayer)       [(20, None, 3)]           0         
                                                                 
 gru_68 (GRU)                (20, 2)                   42        
                                                                 
 dense_30 (Dense)            (20, 2)                   6         
                                                                 
Total params: 48
Trainable params: 48
Non-trainable params: 0
_________________________________________________________________


In [257]:
m.fit(ob_seqs, next_obs, batch_size=20, epochs=10)

Epoch 1/10


ValueError: in user code:

    File "/Users/Ethan/miniconda3/envs/tf_daif/lib/python3.8/site-packages/keras/engine/training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "/Users/Ethan/miniconda3/envs/tf_daif/lib/python3.8/site-packages/keras/engine/training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/Users/Ethan/miniconda3/envs/tf_daif/lib/python3.8/site-packages/keras/engine/training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "/Users/Ethan/miniconda3/envs/tf_daif/lib/python3.8/site-packages/keras/engine/training.py", line 860, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/Users/Ethan/miniconda3/envs/tf_daif/lib/python3.8/site-packages/keras/engine/training.py", line 918, in compute_loss
        return self.compiled_loss(
    File "/Users/Ethan/miniconda3/envs/tf_daif/lib/python3.8/site-packages/keras/engine/compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/Users/Ethan/miniconda3/envs/tf_daif/lib/python3.8/site-packages/keras/losses.py", line 141, in __call__
        losses = call_fn(y_true, y_pred)
    File "/Users/Ethan/miniconda3/envs/tf_daif/lib/python3.8/site-packages/keras/losses.py", line 245, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/Users/Ethan/miniconda3/envs/tf_daif/lib/python3.8/site-packages/keras/losses.py", line 1329, in mean_squared_error
        return backend.mean(tf.math.squared_difference(y_pred, y_true), axis=-1)

    ValueError: Dimensions must be equal, but are 10 and 20 for '{{node mean_squared_error/SquaredDifference}} = SquaredDifference[T=DT_FLOAT](model_47/dense_37/BiasAdd, IteratorGetNext:1)' with input shapes: [20,10,2], [20,2].


In [247]:
res = m(ob_seqs[0:20])

In [248]:
res[0]

<tf.Tensor: shape=(20, 10, 2), dtype=float32, numpy=
array([[[-0.03126741, -0.05007739],
        [-0.02838155, -0.00308725],
        [-0.03572483, -0.00703882],
        [-0.12308189, -0.33903465],
        [-0.09099328, -0.21175347],
        [-0.15656376, -0.48039535],
        [-0.17280677, -0.56211597],
        [-0.09679789, -0.25665036],
        [-0.09596224, -0.23660131],
        [-0.07447534, -0.14166676]],

       [[-0.09012927, -0.25503004],
        [-0.06786623, -0.12630445],
        [-0.06517889, -0.0879531 ],
        [-0.0753606 , -0.10781813],
        [-0.15388907, -0.41995582],
        [-0.16208252, -0.4539302 ],
        [-0.09656087, -0.1943801 ],
        [-0.12658402, -0.30111074],
        [-0.09610697, -0.17922345],
        [-0.1653356 , -0.4642073 ]],

       [[ 0.00175663,  0.08846912],
        [-0.10092825, -0.24563871],
        [-0.12627089, -0.31458697],
        [-0.09916592, -0.19435771],
        [-0.07646907, -0.09792791],
        [-0.09629729, -0.16202733],
       

In [223]:
res[1]

<tf.Tensor: shape=(10, 10, 2), dtype=float32, numpy=
array([[[-0.36397788,  0.0294749 ],
        [-0.48029938,  0.01573997],
        [-0.51549274, -0.00554507],
        [-0.50096333, -0.02819019],
        [-0.51849884, -0.03603037],
        [-0.4956515 , -0.04518281],
        [-0.4919299 , -0.04698842],
        [-0.5167043 , -0.04562606],
        [-0.5176949 , -0.04506196],
        [-0.5242841 , -0.04514759]],

       [[-0.3648733 ,  0.04206948],
        [-0.4807293 ,  0.04454088],
        [-0.51710445,  0.03400522],
        [-0.5260778 ,  0.02312428],
        [-0.5013063 ,  0.01332644],
        [-0.50671595,  0.01171992],
        [-0.52894664,  0.00859705],
        [-0.5185139 ,  0.00654676],
        [-0.52903926,  0.00418232],
        [-0.50056595,  0.00295787]],

       [[-0.35582137,  0.06193205],
        [-0.4635372 ,  0.05734254],
        [-0.50165814,  0.04938255],
        [-0.52453876,  0.04110029],
        [-0.5341751 ,  0.03280196],
        [-0.5287185 ,  0.02695066],
       